# Generated by Django 5.2.15 on 2026-07-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("current_location", models.CharField(max_length=255)),
                ("pickup_location", models.CharField(max_length=255)),
                ("dropoff_location", models.CharField(max_length=255)),
                ("current_cycle_used", models.FloatField()),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("total_miles", models.FloatField(blank=True, null=True)),
                ("total_drive_hours", models.FloatField(blank=True, null=True)),
                ("is_legal", models.BooleanField(default=True)),
                ("cycle_used_at_end", models.FloatField(blank=True, null=True)),
                ("not_legal_reason", models.TextField(blank=True, default="")),
                ("route_geometry", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("fuel", "Fuel"),
                            ("rest", "Rest"),
                            ("pickup", "Pickup"),
                            ("dropoff", "Dropoff"),
                            ("break", "Break"),
                            ("deadhead", "Deadhead"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "location_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField(blank=True, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["arrival_time"],
            },
        ),
        migrations.CreateModel(
            name="DutyStatusSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("off", "Off Duty"),
                            ("sleeper", "Sleeper Berth"),
                            ("driving", "Driving"),
                            ("on", "On Duty Not Driving"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_lng", models.FloatField(blank=True, null=True)),
                (
                    "location_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
